// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txcwplnfuillccxhmqsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4Y3dwbG5mdWlsbGNjeGhtcXN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODMwMDYsImV4cCI6MjA2ODc1OTAwNn0.CxBzktrciFLDbWIqJm1RrywGYozGZMjx2Vrn6g0TnN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});